#! /bin/bash


filesList=`grep \\lecture{ lectures.tex | grep -v % | sed 's/\\\lecture{//g' |
sed 's/}//g'`

files=($filesList)

for i in "${!files[@]}"; do
    f=${files[i]}
    sof="${f}-subsidiary.org"
    if [ ! -f ${f}-subsidiary.pdf ]; then
	lesson=`head ${f}.tex | grep 'lesson{' | sed 's/.lesson{//' | sed 's/}//'`
	keywords=`head -35 ${f}.tex | grep 'keywords{' | sed 's/.keywords{//' |
    sed 's/}//'`
	next=${files[i+1]}
	if [ next == "" ]; then
	    next=${files[0]}
	fi
	prev=${files[i-1]}
	cat > $sof << EOF
#+TITLE: Advanced Machine Learning Subsidary Notes
#+SUBTITLE: Lecture $i: $lesson

* Keywords
  * $keywords

* Main Points

**

* Exercises

**

* Experiments

**

* COMMENT [[file:pdf/${f}.pdf][PDF]] [[file:pdf/${f}_prn.pdf][Print]]
* COMMENT [[file:${prev}-subsidiary.org][Previous]] [[file:${next}-subsidiary.org][Next]]
* Options                                                  :ARCHIVE:noexport:
#+BEGIN_OPTIONS
#+OPTIONS: toc:nil
#+LATEX_HEADER: \usepackage[a4paper,margin=20mm]{geometry}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amsfonts}
#+LATEX_HEADER: \usepackage{stmaryrd}
#+LATEX_HEADER: \usepackage{bm}
#+LaTeX_HEADER: \usepackage{minted}
#+LaTeX_HEADER: \usemintedstyle{emacs}
#+LaTeX_HEADER: \usepackage[T1]{fontenc}
#+LaTeX_HEADER: \usepackage[scaled]{beraserif}
#+LaTeX_HEADER: \usepackage[scaled]{berasans}
#+LaTeX_HEADER: \usepackage[scaled]{beramono}
#+LATEX_HEADER: \newcommand{\tr}{\textsf{T}}
#+LATEX_HEADER: \newcommand{\grad}{\bm{\nabla}}
#+LATEX_HEADER: \newcommand{\av}[2][]{\mathbb{E}_{#1\!}\left[ #2 \right]}
#+LATEX_HEADER: \newcommand{\Prob}[2][]{\mathbb{P}_{#1\!}\left[ #2 \right]}
#+LATEX_HEADER: \newcommand{\logg}[1]{\log\!\left( #1 \right)}
#+LATEX_HEADER: \newcommand{\pred}[1]{\left\llbracket { \small #1} \right\rrbracket}
#+LATEX_HEADER: \newcommand{\e}[1]{{\rm e}^{#1}}
#+LATEX_HEADER: \newcommand{\dd}{\mathrm{d}}
#+LATEX_HEADER: \DeclareMathAlphabet{\mat}{OT1}{cmss}{bx}{n}
#+LATEX_HEADER: \newcommand{\normal}[2]{\mathcal{N}\!\left(#1 \big| #2 \right)}
#+LATEX_HEADER: \newcounter{eqCounter}
#+LATEX_HEADER: \setcounter{eqCounter}{0}
#+LATEX_HEADER: \newcommand{\explanation}{\setcounter{eqCounter}{0}\renewcommand{\labelenumi}{(\arabic{enumi})}}
#+LATEX_HEADER: \newcommand{\eq}[1][=]{\stepcounter{eqCounter}\stackrel{\text{\tiny(\arabic{eqCounter})}}{#1}}
#+LATEX_HEADER: \newcommand{\argmax}{\mathop{\mathrm{argmax}}}
#+LATEX_HEADER: \newcommand{\Dist}[2][Binom]{\mathrm{#1}\left( \strut {#2} \right)}
#+END_OPTIONS

EOF
    fi
done
