#! /bin/bash

files=`grep "\\lecture{" lectures.tex | grep -v % | sed 's/\\\lecture{//g' | sed 's/}//g'`

ssh-agent
for f in $files
do
    if [ -f videos/${f}.mp4 ]; then	
	if [ videos/${f}.mp4 -nt videos/${f}-time ]; then
	    echo "Need to copy video file ${f}.mp4 to stafflogin"
	    scp videos/${f}.mp4 apb1@stafflogin.ecs.soton.ac.uk:/notes/comp6208/lectures/videos/${f}.mp4
	fi
    fi
    if [ pdf/${f}_prn_8.pdf  -nt $f.tex ]; then
        continue
    fi
    echo "Processing $f"
    outf=pdf/$f.pdf
    if echo $f | /usr/bin/pdflatex -shell-escape lectures; then
	echo "OK"
    else
	echo "Error"
	exit 1;
    fi
    echo $f | /usr/bin/pdflatex lectures &> /dev/null
    ppower4 lectures.pdf $f.pdf
    outf=pdf/${f}_prn.pdf
    mv lectures.pdf $outf
    pdfjam --nup 2x4 --no-landscape --outfile pdf/${f}_prn_8.pdf pdf/${f}_prn.pdf
    pdfjam --nup 2x2 --outfile pdf/${f}_prn_4.pdf pdf/${f}_prn.pdf
    dir=$cwd
    destination="/home/apb/teaching/courses/comp6208/github/site/"
    if [ -f src/${f}.ipynb ]
    then
	cp src/${f}.ipynb "${destination}/notebook"
    fi
    destination="${destination}/lecture_pdf/"
    if [ -f ../problems/${f}-questions.pdf ]
    then
	cp ../problems/${f}-questions.pdf ${destination}
	cp ../problems/${f}-answers.pdf ${destination}
    fi
    cp $outf ${destination}
    cp pdf/$f.pdf ${destination}
    cp pdf/${f}_prn_8.pdf ${destination}
    cp pdf/${f}_prn_4.pdf ${destination}
    # Video
done
#cmd="pdftk "
#for f in $files; do
#    cmd="$cmd pdf/${f}_prn_8.pdf "
#done
#cmd="$cmd cat output pdf/lectures_8.pdf"
#echo $cmd
#$cmd
#scp pdf/lectures_8.pdf ${destination}
#lecturehtml
lecturehtml
